# Generated by Django 4.2.7 on 2023-11-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora')),
                ('vasodilatation_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Taxa de Vasodilatação')),
                ('rest_diameter', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Diâmetro em Repouso')),
                ('max_diameter', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Diâmetro Máximo')),
                ('max_blood_flow_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Taxa Máxima de Fluxo Sanguíneo')),
                ('vessel_wall_thickness', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Espessura da Parede Vascular')),
                ('rest_graph', models.ImageField(blank=True, null=True, upload_to='exam_images/', verbose_name='Gráfico Rest')),
                ('after_cuff_released_graph', models.ImageField(blank=True, null=True, upload_to='exam_images/', verbose_name='Gráfico After Cuff Released')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
