# Generated by Django 4.2.7 on 2023-11-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_exam_patient_alter_exam_max_blood_flow_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='exam_videos/', verbose_name='Vídeo do Exame'),
        ),
    ]
