# Generated by Django 4.2.7 on 2023-11-14 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_exam_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='max_blood_flow_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Taxa Máxima de Fluxo Sanguíneo'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='max_diameter',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Diâmetro Máximo'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='rest_diameter',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Diâmetro em Repouso'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='vasodilatation_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Taxa de Vasodilatação'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='vessel_wall_thickness',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Espessura da Parede Vascular'),
        ),
    ]
