# Generated by Django 4.2.7 on 2023-11-14 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0005_alter_exam_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Parceiro'),
        ),
    ]
