# Generated by Django 4.2.7 on 2023-11-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_exam_processed_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='processing_status',
            field=models.CharField(default='queued', max_length=30, verbose_name='Status do processamento'),
        ),
    ]
