# Generated by Django 4.2.7 on 2023-11-22 21:53

from django.db import migrations, models
import exam.models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_exam_processing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='segmentation_video_file',
            field=models.FileField(blank=True, null=True, upload_to='segmentation_exam_videos/', verbose_name='Vídeo segmentado do Exame'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='max_diameter',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='mm', max_digits=5, null=True, verbose_name='Diâmetro Máximo'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='processing_status',
            field=models.CharField(default='queued', max_length=1024, verbose_name='Status do processamento'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='rest_diameter',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='mm', max_digits=5, null=True, verbose_name='Diâmetro em Repouso'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='vasodilatation_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='%', max_digits=5, null=True, verbose_name='Taxa de Vasodilatação'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='vessel_wall_thickness',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='mm', max_digits=5, null=True, verbose_name='Espessura da Parede Vascular'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='video_file',
            field=models.FileField(upload_to=exam.models.get_upload_filename, verbose_name='Vídeo do Exame'),
        ),
    ]
