# Generated by Django 4.2.7 on 2023-11-11 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_record', models.CharField(max_length=20, verbose_name='Prontuário Médico')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('address', models.CharField(blank=True, max_length=70, null=True, verbose_name='Endereço')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=30, null=True, verbose_name='Estado')),
                ('country', models.CharField(blank=True, max_length=30, null=True, verbose_name='País')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('cellphone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular')),
                ('birth_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data de Nascimento')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True, verbose_name='Gênero')),
                ('blood', models.CharField(blank=True, choices=[('A-', 'A-'), ('A+', 'A+'), ('AB-', 'AB-'), ('AB+', 'AB+'), ('B-', 'B-'), ('B+', 'B+'), ('O-', 'O-'), ('O+', 'O+')], max_length=3, null=True, verbose_name='Tipo Sanguíneo')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Altura')),
                ('obs', models.CharField(blank=True, max_length=140, null=True, verbose_name='Observações')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Parceiro')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
