# Generated by Django 4.2.7 on 2023-11-11 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['first_name']},
        ),
        migrations.RemoveField(
            model_name='partner',
            name='name',
        ),
    ]
