# Generated by Django 4.2.7 on 2023-11-22 21:53

from django.db import migrations
import menu.models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_partner_options'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='partner',
            managers=[
                ('objects', menu.models.PartnerManager()),
            ],
        ),
    ]
